name: 'Builder'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build
        run: |
          yarn install
          yarn build
      - name: Push
        run: |
          git config --local user.name "Builder"
          git config --local user.email "builder@workflow.github.com"
          git checkout -b build/main
          git add -f dist
          git commit -m "Build"
          git push -f
